import type { NextPage } from 'next'
import Head from 'next/head'
import 'tailwindcss/tailwind.css'
import Login from "../components/Login";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Based Media</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='grid place-items-center h-screen w-screen bg-neutral-900'>
        <Login/>
      </div>

    </>
  )
}

export default Home
