import type { NextPage } from 'next'
import Head from 'next/head'
import 'tailwindcss/tailwind.css'
import Header from "../components/Header";
import {useState} from "react";
import axios from "axios";
import PostItem from "../components/PostItem";
import {IPost} from "../types/post";

interface HomePageProps {
  posts: [IPost]
}

const Home: NextPage<HomePageProps> = ({posts}) => {

  return (
    <>
      <Head>
        <title>Based Media</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='bg-neutral-900 w-screen h-screen'>
        <Header/>
        <div className='flex pt-14 justify-center w-full h-full overflow-auto'>
          <div className='flex flex-col pt-8 gap-8 w-full max-w-xl h-full'>
            {posts.map((post: IPost) => <PostItem key={post.id} post={post}/>)}
          </div>

        </div>
      </div>

    </>
  )
}

export default Home;

export const getStaticProps = async () => {

  const response = await axios.get('http://127.0.0.1:8000/posts')
  const posts = response.data

  return {
    props: {posts}
  }
}

